### ISSUE TITLE
h1 title smaller than h2 title

### ISSUE THREAD

**Issue by thecross-fr** [mamcmanus/brutalist#4]
Hello,

Thanks for the template, it generates nice websites.
I have one remark regarding title size.
As shown in the picture below, h1 titles are smaller than h2 titles. Temporarily workaround is not to use h1 titles.
![Screenshot_20190428_122417](https://user-images.githubusercontent.com/35191807/56862956-b1396500-69b0-11e9-97f8-e2c102ffd818.png)

Pelican version is 3.7.1-1
Brutalist theme is at the latest version on the 28th of April 2019

**Comment by thomasgtaylor** [comment]
@LThecross Adding this to the `main.css` fixed the issue:

```css
.article article .content h1 {
  font-size: 1.6em;
  padding-bottom: 0.75em;
  padding-top: 1.5em;
  font-weight: 900;
}
```
